In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data=pd.read_csv('creditcard.csv',header=None)

In [3]:
data.head()

0         1         2         3         4         5         6         7   \
0   0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         8         9   ...        21        22        23        24        25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

         26        27        28      29  30  
0 -0.189115  0.133558 -0.021053  149.62   0  
1  0.125895 -0.008983  0.014724    2.69   0  
2 -0.139097 -0.055353 -0.059752  378.66   0  
3 -0.221929  0.062723  0.061458  123.50   0  
4  0.502292  0.219422  0.215153   69.99   0  

[5 rows x 31 columns]

In [4]:
data.keys()

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
           dtype='int64')

In [5]:
data

0         1         2         3         4         5         6   \
0      0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1      0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2      1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3      1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4      2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5      2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6      4  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7      7 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8      7 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9      9 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10    10  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11    10  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12    10  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230   
13    11  1.069374  0.287722  0.828613  2.712520 -0.178398  0.337544   
14    12 -2.791855 -0.327771  1.641750  1.767473 -0.136588  0.807596   
15    12 -0.752417  0.345485  2.057323 -1.468643 -1.158394 -0.077850   
16    12  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069   
17    13 -0.436905  0.918966  0.924591 -0.727219  0.915679 -0.127867   
18    14 -5.401258 -5.450148  1.186305  1.736239  3.049106 -1.763406   
19    15  1.492936 -1.029346  0.454795 -1.438026 -1.555434 -0.720961   
20    16  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109   
21    17  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038   
22    18  1.166616  0.502120 -0.067300  2.261569  0.428804  0.089474   
23    18  0.247491  0.277666  1.185471 -0.092603 -1.314394 -0.150116   
24    22 -1.946525 -0.044901 -0.405570 -1.013057  2.941968  2.955053   
25    22 -2.074295 -0.121482  1.322021  0.410008  0.295198 -0.959537   
26    23  1.173285  0.353498  0.283905  1.133563 -0.172577 -0.916054   
27    23  1.322707 -0.174041  0.434555  0.576038 -0.836758 -0.831083   
28    23 -0.414289  0.905437  1.727453  1.473471  0.007443 -0.200331   
29    23  1.059387 -0.175319  1.266130  1.186110 -0.786002  0.578435   
..   ...       ...       ...       ...       ...       ...       ...   
633  481 -2.752124 -3.232168  0.873036  0.108217 -2.451279  0.486159   
634  481  1.215468 -0.071342  1.048697  0.724719 -0.694532  0.041879   
635  483  1.039674 -0.329296  1.073431  1.547480 -0.595510  1.090970   
636  483 -0.792724  0.946688  2.245149  1.167398 -0.625405 -0.449979   
637  484 -1.123243 -0.601733  1.866232  0.373544 -0.165149  1.602099   
638  484  1.093370  0.108995  0.100227  0.913194  0.084986  0.030469   
639  484 -0.928088  0.398194  1.741131  0.182673  0.966387 -0.901004   
640  484  1.060623  0.077500 -0.049338  0.546163  0.004831 -0.732323   
641  487 -0.517981  0.723072  1.401196  0.772313  0.671651  0.847780   
642  487  1.164359 -0.283474 -0.247022  0.192064 -0.327522 -0.822581   
643  487  0.174857  2.035550 -1.866661  1.420853  0.829644 -1.683505   
644  488  0.986168 -0.550923  1.140934  0.757901 -1.038890  0.476782   
645  489 -0.932349  0.789123  0.534111  1.140724 -0.448967 -0.288526   
646  490 -0.215043  0.652190  1.107882  1.265935  2.366300  4.393732   
647  490  0.716662 -1.097812  0.629443  1.939510 -0.494739  1.819965   
648  491 -0.946412  0.609500  1.201710  0.113074 -0.210132 -0.954009   
649  491  1.196288  0.217099  0.402596  0.921664 -0.252045 -0.392240   
650  491  1.130024 -0.060944  0.662074  1.033990 -0.441560  0.310187   
651  492 -0.789890 -1.379371  0.171334 -1.636756 -2.807266  0.726236   
652  493  1.219725 -0.481149 -0.324351 -1.552562 -0.258357 -0.519342   
653  494  0.058501  1.058661  1.076857  1.589043 -0.400077 -0.677461   
654  495 -0.239505 -3.940241 -0.147576 -0.671347 -2.239256  0.908178   
655  496 -0.606284 -0.090112  2.012027  0.352728 -0.210154  0.513719   
656  496 -2.009893  0.522693  2.043510  0.2235

In [8]:
print(data.iloc[:,:30])

      0         1         2         3         4         5         6   \
0      0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1      0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2      1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3      1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4      2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5      2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6      4  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7      7 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8      7 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9      9 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10    10  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11    10  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12    10  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.75

In [12]:
train=data.iloc[:,:30]

In [13]:
train

0         1         2         3         4         5         6   \
0      0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1      0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2      1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3      1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4      2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5      2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6      4  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7      7 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8      7 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9      9 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10    10  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11    10  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12    10  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230   
13    11  1.069374  0.287722  0.828613  2.712520 -0.178398  0.337544   
14    12 -2.791855 -0.327771  1.641750  1.767473 -0.136588  0.807596   
15    12 -0.752417  0.345485  2.057323 -1.468643 -1.158394 -0.077850   
16    12  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069   
17    13 -0.436905  0.918966  0.924591 -0.727219  0.915679 -0.127867   
18    14 -5.401258 -5.450148  1.186305  1.736239  3.049106 -1.763406   
19    15  1.492936 -1.029346  0.454795 -1.438026 -1.555434 -0.720961   
20    16  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109   
21    17  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038   
22    18  1.166616  0.502120 -0.067300  2.261569  0.428804  0.089474   
23    18  0.247491  0.277666  1.185471 -0.092603 -1.314394 -0.150116   
24    22 -1.946525 -0.044901 -0.405570 -1.013057  2.941968  2.955053   
25    22 -2.074295 -0.121482  1.322021  0.410008  0.295198 -0.959537   
26    23  1.173285  0.353498  0.283905  1.133563 -0.172577 -0.916054   
27    23  1.322707 -0.174041  0.434555  0.576038 -0.836758 -0.831083   
28    23 -0.414289  0.905437  1.727453  1.473471  0.007443 -0.200331   
29    23  1.059387 -0.175319  1.266130  1.186110 -0.786002  0.578435   
..   ...       ...       ...       ...       ...       ...       ...   
633  481 -2.752124 -3.232168  0.873036  0.108217 -2.451279  0.486159   
634  481  1.215468 -0.071342  1.048697  0.724719 -0.694532  0.041879   
635  483  1.039674 -0.329296  1.073431  1.547480 -0.595510  1.090970   
636  483 -0.792724  0.946688  2.245149  1.167398 -0.625405 -0.449979   
637  484 -1.123243 -0.601733  1.866232  0.373544 -0.165149  1.602099   
638  484  1.093370  0.108995  0.100227  0.913194  0.084986  0.030469   
639  484 -0.928088  0.398194  1.741131  0.182673  0.966387 -0.901004   
640  484  1.060623  0.077500 -0.049338  0.546163  0.004831 -0.732323   
641  487 -0.517981  0.723072  1.401196  0.772313  0.671651  0.847780   
642  487  1.164359 -0.283474 -0.247022  0.192064 -0.327522 -0.822581   
643  487  0.174857  2.035550 -1.866661  1.420853  0.829644 -1.683505   
644  488  0.986168 -0.550923  1.140934  0.757901 -1.038890  0.476782   
645  489 -0.932349  0.789123  0.534111  1.140724 -0.448967 -0.288526   
646  490 -0.215043  0.652190  1.107882  1.265935  2.366300  4.393732   
647  490  0.716662 -1.097812  0.629443  1.939510 -0.494739  1.819965   
648  491 -0.946412  0.609500  1.201710  0.113074 -0.210132 -0.954009   
649  491  1.196288  0.217099  0.402596  0.921664 -0.252045 -0.392240   
650  491  1.130024 -0.060944  0.662074  1.033990 -0.441560  0.310187   
651  492 -0.789890 -1.379371  0.171334 -1.636756 -2.807266  0.726236   
652  493  1.219725 -0.481149 -0.324351 -1.552562 -0.258357 -0.519342   
653  494  0.058501  1.058661  1.076857  1.589043 -0.400077 -0.677461   
654  495 -0.239505 -3.940241 -0.147576 -0.671347 -2.239256  0.908178   
655  496 -0.606284 -0.090112  2.012027  0.352728 -0.210154  0.513719   
656  496 -2.009893  0.522693  2.043510  0.2235

In [16]:
test=data.iloc[:,-1]

In [17]:
test

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
633    0
634    0
635    0
636    0
637    0
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    0
649    0
650    0
651    0
652    0
653    0
654    0
655    0
656    0
657    0
658    0
659    0
660    0
661    0
662    0
Name: 30, Length: 663, dtype: int64

In [19]:
from sklearn.decomposition import PCA  #forgot to include in first line

In [20]:
pca=PCA(n_components=10)

In [21]:
Df_train=pd.DataFrame(train)

In [22]:
Df_test=pd.DataFrame(test)

In [23]:
Df_train.shape

(663, 30)

In [24]:
Df_test.shape

(663, 1)

In [25]:
x=Df_train

In [26]:
y=Df_test

In [27]:
x

0         1         2         3         4         5         6   \
0      0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1      0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2      1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3      1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4      2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
5      2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728   
6      4  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708   
7      7 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118   
8      7 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818   
9      9 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761   
10    10  1.449044 -1.176339  0.913860 -1.375667 -1.971383 -0.629152   
11    10  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027   
12    10  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230   
13    11  1.069374  0.287722  0.828613  2.712520 -0.178398  0.337544   
14    12 -2.791855 -0.327771  1.641750  1.767473 -0.136588  0.807596   
15    12 -0.752417  0.345485  2.057323 -1.468643 -1.158394 -0.077850   
16    12  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069   
17    13 -0.436905  0.918966  0.924591 -0.727219  0.915679 -0.127867   
18    14 -5.401258 -5.450148  1.186305  1.736239  3.049106 -1.763406   
19    15  1.492936 -1.029346  0.454795 -1.438026 -1.555434 -0.720961   
20    16  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109   
21    17  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038   
22    18  1.166616  0.502120 -0.067300  2.261569  0.428804  0.089474   
23    18  0.247491  0.277666  1.185471 -0.092603 -1.314394 -0.150116   
24    22 -1.946525 -0.044901 -0.405570 -1.013057  2.941968  2.955053   
25    22 -2.074295 -0.121482  1.322021  0.410008  0.295198 -0.959537   
26    23  1.173285  0.353498  0.283905  1.133563 -0.172577 -0.916054   
27    23  1.322707 -0.174041  0.434555  0.576038 -0.836758 -0.831083   
28    23 -0.414289  0.905437  1.727453  1.473471  0.007443 -0.200331   
29    23  1.059387 -0.175319  1.266130  1.186110 -0.786002  0.578435   
..   ...       ...       ...       ...       ...       ...       ...   
633  481 -2.752124 -3.232168  0.873036  0.108217 -2.451279  0.486159   
634  481  1.215468 -0.071342  1.048697  0.724719 -0.694532  0.041879   
635  483  1.039674 -0.329296  1.073431  1.547480 -0.595510  1.090970   
636  483 -0.792724  0.946688  2.245149  1.167398 -0.625405 -0.449979   
637  484 -1.123243 -0.601733  1.866232  0.373544 -0.165149  1.602099   
638  484  1.093370  0.108995  0.100227  0.913194  0.084986  0.030469   
639  484 -0.928088  0.398194  1.741131  0.182673  0.966387 -0.901004   
640  484  1.060623  0.077500 -0.049338  0.546163  0.004831 -0.732323   
641  487 -0.517981  0.723072  1.401196  0.772313  0.671651  0.847780   
642  487  1.164359 -0.283474 -0.247022  0.192064 -0.327522 -0.822581   
643  487  0.174857  2.035550 -1.866661  1.420853  0.829644 -1.683505   
644  488  0.986168 -0.550923  1.140934  0.757901 -1.038890  0.476782   
645  489 -0.932349  0.789123  0.534111  1.140724 -0.448967 -0.288526   
646  490 -0.215043  0.652190  1.107882  1.265935  2.366300  4.393732   
647  490  0.716662 -1.097812  0.629443  1.939510 -0.494739  1.819965   
648  491 -0.946412  0.609500  1.201710  0.113074 -0.210132 -0.954009   
649  491  1.196288  0.217099  0.402596  0.921664 -0.252045 -0.392240   
650  491  1.130024 -0.060944  0.662074  1.033990 -0.441560  0.310187   
651  492 -0.789890 -1.379371  0.171334 -1.636756 -2.807266  0.726236   
652  493  1.219725 -0.481149 -0.324351 -1.552562 -0.258357 -0.519342   
653  494  0.058501  1.058661  1.076857  1.589043 -0.400077 -0.677461   
654  495 -0.239505 -3.940241 -0.147576 -0.671347 -2.239256  0.908178   
655  496 -0.606284 -0.090112  2.012027  0.352728 -0.210154  0.513719   
656  496 -2.009893  0.522693  2.043510  0.2235

In [28]:
y

30
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
..   ..
633   0
634   0
635   0
636   0
637   0
638   0
639   0
640   0
641   0
642   0
643   0
644   0
645   0
646   0
647   0
648   0
649   0
650   0
651   0
652   0
653   0
654   0
655   0
656   0
657   0
658   0
659   0
660   0
661   0
662   0

[663 rows x 1 columns]

In [40]:
pca=PCA(n_components=10)

In [41]:
x=pca.fit_transform(x)

In [42]:
x.shape

(663, 10)

In [51]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.22,random_state=50)

In [44]:
train_x.shape

(517, 10)

In [45]:
test_x.shape

(146, 10)

In [46]:
train_y.shape

(517, 1)

In [47]:
test_y.shape

(146, 1)

In [52]:
lg=LogisticRegression()
lg.fit(train_x,train_y)
pred=lg.predict(test_x)
print("accuracy_score:",accuracy_score(pred,test_y))
print(confusion_matrix(test_y,pred))
print(classification_report(test_y,pred))

accuracy_score: 0.952054794520548
[[139   0]
 [  7   0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       139
           1       0.00      0.00      0.00         7

   micro avg       0.95      0.95      0.95       146
   macro avg       0.48      0.50      0.49       146
weighted avg       0.91      0.95      0.93       146



In [53]:
gnb=GaussianNB()
gnb.fit(train_x,train_y)

predgnb=gnb.predict(test_x)
print(accuracy_score(test_y,predgnb))
print(confusion_matrix(test_y,predgnb))
print(classification_report(test_y,predgnb))

0.952054794520548
[[139   0]
 [  7   0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       139
           1       0.00      0.00      0.00         7

   micro avg       0.95      0.95      0.95       146
   macro avg       0.48      0.50      0.49       146
weighted avg       0.91      0.95      0.93       146



In [54]:
svc=SVC()
svc.fit(train_x,train_y)

predsvc=svc.predict(test_x)
print(accuracy_score(test_y,predsvc))
print(confusion_matrix(test_y,predsvc))
print(classification_report(test_y,predsvc))

0.952054794520548
[[139   0]
 [  7   0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       139
           1       0.00      0.00      0.00         7

   micro avg       0.95      0.95      0.95       146
   macro avg       0.48      0.50      0.49       146
weighted avg       0.91      0.95      0.93       146



In [55]:
dtc=DecisionTreeClassifier()
dtc.fit(train_x,train_y)

preddtc=dtc.predict(test_x)
print(accuracy_score(test_y,preddtc))
print(confusion_matrix(test_y,preddtc))
print(classification_report(test_y,preddtc))

0.9178082191780822
[[132   7]
 [  5   2]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96       139
           1       0.22      0.29      0.25         7

   micro avg       0.92      0.92      0.92       146
   macro avg       0.59      0.62      0.60       146
weighted avg       0.93      0.92      0.92       146



In [56]:
knc=KNeighborsClassifier()
knc.fit(train_x,train_y)

predknc=knc.predict(test_x)
print(accuracy_score(test_y,predknc))
print(confusion_matrix(test_y,predknc))
print(classification_report(test_y,predknc))

0.952054794520548
[[139   0]
 [  7   0]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       139
           1       0.00      0.00      0.00         7

   micro avg       0.95      0.95      0.95       146
   macro avg       0.48      0.50      0.49       146
weighted avg       0.91      0.95      0.93       146



In [ ]:
#not applied any enesamble techinque and cross val because accuracy score is coming .95